create database customer_behaviour;

show databases;

use customer_behaviour;

Select * from customer limit 10;

-- Q1. What is the Total Revenue generated by female vr male customer?
Select gender, sum(purchase_amount) as Total_Revenue from customer group by gender;

-- Q2. Which customer used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount from customer where 
discount_applied = "YES" and purchase_amount >= (Select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with highest average review rating?
Select item_purchased, round(avg(review_rating),2) as "Average Product Rating" from customer
group by item_purchased order by avg(review_rating) desc limit 5;

-- Q4. Compare the average purchase amounts between Standard and Express shipping?
Select shipping_type, round(avg(purchase_amount),2) as "Average Purchase Amount" from customer group by shipping_type 
having shipping_type in ("Standard","Express");

-- Q5. Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status, count(customer_id), sum(purchase_amount) as "Total Revenue", avg(purchase_amount) as "Average Spend" 
from customer group by subscription_status order by "Total Revenue", "Average Spend" desc;

-- Q6. Which 5 products have the highest percentage of purchase with discount applied?
Select item_purchased, sum(case when discount_applied = "Yes" Then 1 Else 0 END) * 100/ count(*) as discount_percentage
from customer group by item_purchased order by discount_percentage desc limit 5;

-- Q7. Segment customers into New, Returning and Loyal based on their total number of previous purchases,
-- and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases, case
when previous_purchases = 1 Then "New"
when previous_purchases between 2 and 10 Then "Returning"
Else "Loyal"
End as customer_segment from customer)
Select customer_segment, count(*) as "Number of customers" from customer_type group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (Select category, item_purchased, count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank 
from customer group by category, item_purchased)
Select item_rank, category, item_purchased, total_orders from item_counts where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,count(customer_id) as repeat_buyers from customer where previous_purchases > 5 
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
Select age_group, sum(purchase_amount) as revenue from customer group by age_group order by revenue desc;